### ISSUE TITLE
checking other coins

### ISSUE THREAD

**Issue by ghost** [Der-Eddy/telegram_crypto_bot#1]
getting the error when checking /coin ltc and others
somehow only neo seems to work

`telegram.utils.promise - ERROR - An uncaught error was raised while running the promise
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/telegram/utils/promise.py", line 42, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "main.py", line 76, in coin
    euro = float(json[0]["price_eur"])
KeyError: 0`

**Comment by Der-Eddy** [comment]
Thats an issue with the [coinmarketcap.com API](https://coinmarketcap.com/api/), you need to provide the `id` listed on coinmarketcap.com, which is basically the full name in lowercase  
In case of Litecoin you would need to run `/coin litecoin`

**Comment by ghost** [comment]
thanks!

**Comment by Der-Eddy** [comment]
The bot will now recognice a lot of symbols (atleast the ones listed at Bittrex)
so `/coin ltc` works now!

![07-01-2018 22-38-47](https://user-images.githubusercontent.com/1234101/34654409-8a92c332-f3fb-11e7-9b37-ac1bb45c0503.png)
